site_name: Interpreter RegEx
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
